import { app } from '@azure/functions';

import './aiGenerate';
import './dbPing';
import './glUpload';
import './health';
import './industries';
import './chartOfAccounts';
import './mappingSuggest';
import './masterclients';
import './userClients';
import './datapointConfigs/create';
import './datapointConfigs/list';
import './datapointConfigs/update';
import './clientFiles';
import './clientFileSheets';
import './clientFileEntities';
import './clientEntities';
import './clientHeaderMappings';
import './fileRecords';
import './entityDistributionPresetDetails';
import './entityDistributions';
import './entityDistributionPresets';
import './entityAccountMappings';
import './entityMappingPresetDetails';
import './entityMappingPresets';
import './entityScoaActivity';
import './entityScoaDistribution';
import './operationScoaActivity';

export default app;
